- CMakeLists.txt
This version comparison is wrong.
I am on cmake 3.10, which is not inferior to 3.2, although by numeric comparison it is.
I replace this by VERSION_LESS/VERSION_GREATER which according to manual are present in cmake since 3.0.2 at least.
> fix the check which identifies cmake as a legacy version

- src/adlmidi_opl3.cpp
- src/adlmidi_private.hpp
AddressSanitizer raises an issue in latest versions.
```==6765==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new vs free) on 0x603000001900```
1. This is because instances of **OPLChipBase** are kept under the smart pointer **AdlMIDI_CPtr**, which invokes **free** in the destructor, not **delete**.
2. Moreover, there is a vector of **AdlMIDI_CPtr**. It suffers from the same problem in C++98 as **vector<auto_ptr<>>**. Contents are destroyed when the vector grows because of copy.
I took a few actions to solve this.
1. I put OPLChipBase instances in shared pointers. Because **std::shared_ptr** is forbidden, I implement **AdlMIDI_SPtr** in replacement.
2. I protect **AdlMIDI_CPtr** against copies with private visibility.
> fix memory management issues

- src/adlmidi_private.hpp
It's a kind of moment when you hover your old code and realize your error.
After some years of implementing stl-like stuff I still can never get a shared_ptr right on first try.
It's a pretty inconsequential mistake bur maybe it will save someone some future hair pulling.
Fixes self-assignment.
> fix SPtr implementation mistake

- src/adlmidi_private.hpp
> fix inclusion of cinttypes on OS X libstdc++

- src/adlmidi_midiplay.cpp
- src/adlmidi_private.hpp
I rewrite your commit https://github.com/Wohlstand/libADLMIDI/commit/09bb3bc4d31ac925a13f51f8fc4944330da158bb to try to stick to original map semantics of ADLMIDI.
It fixes crashes I have occuring in playback.
I call for you to verify this; you're probably the one person there is second to Joel to understand how all this stuff works.
(what a time I have passed trying to fix this stuff, damn :smile:)
> Phys code rewrite

- src/wopl/wopl_file.c
It's implementation-defined whether >> is logical or arithmetic on negative integers.
Force a logical shift by casting.
> fix implementation defined behavior

- src/wopl/wopl_file.c
The loader has a byte intended to hold the null terminator of the name.
`snprintf` does not write this byte if the name takes the maximum size (32).
In the bank loading case it's benign because the memory is initialized with zero.
Not in `WOPL_LoadInstFromMem` where the user provides the structure.
Anyway I correct both cases.
---
In my variant of code I will just remove this byte to save the padding space. I am used to handle strings in binary structs, I will not make use of this safety.
> wopl robustness fix

- src/adlmidi_midiplay.cpp
Just the same thing as the fix proposal in libOPNMIDI
> check LocationData for null on access of vibdelay

- src/adlmidi_midiplay.cpp
Negative pitch bend is broken in one of the function variants.
The one which takes the 14 bit value.
> fix pitchbend

- src/adlmidi_midiplay.cpp
- src/adlmidi_private.hpp
This ADLMIDI code handles the pitchbend sensitivity RPN setting wrong.
It defines `bendsense` according to the RPN MSB, but the `SetRPN` will allow it to take a value from either LSB or MSB, which is an error.
Moreover:
I have found this [definition](http://www.lim.di.unimi.it/IEEE/MIDI/SOT1.HTM#Pitch) of this RPN.
MSB is supposed to be semitones, and LSB in cents.
I add a piece of code which adds consideration for LSB in the computation.
**But**
I've had issues with bizarre sounding pitchbend every now and then, and I try to find why. It's still the case with this patch applied.
For example [this one](http://www.rppmf.com/dream_theater/2005-octavarium/08-dream_theater_2005-octavarium.mid) gets very happy with pitchbend at around 12:15. Timidity is able to get the tone right, but not …
> meaningful handling of pitch bend sensitivity

- CMakeLists.txt
- src/adlmidi_bankmap.h
- src/adlmidi_bankmap.tcc
- src/adlmidi_private.hpp
- test/CMakeLists.txt
- test/bankmap/CMakeLists.txt
- test/bankmap/bank_map.cpp
- test/common/catch.hpp
- test/common/catch_main.cpp
#59 
I create a hashmap container which is specialized for mapping things to bank numbers.
This replaces the current `BankMap`. A unit test is included.
This structure is optimized for worst case, because it's not only easier but also for RT reasons, and it allows for some cache locality (if it was reserved in one block).
The standard containers would not provide the functionality needed, because they do not allow to reserve storage for a fixed number of elements. I have a normal insertion which follows STL semantics, and a policy-based insertion which does not attempt to extend the storage.
Now, I am thinking about storing the instruments in this structure instead of having the indirection into instrument arrays of ADLMIDI. It's because the erasure operations are going to create holes, …
> specialized hash table for bank number mappings

- CMakeLists.txt
- src/adldata.hh
- src/adlmidi_bankmap.h
- src/adlmidi_bankmap.tcc
- src/adlmidi_load.cpp
- src/adlmidi_midiplay.cpp
- src/adlmidi_opl3.cpp
- src/adlmidi_private.cpp
- src/adlmidi_private.hpp
- src/adlmidi_ptr.hpp
- src/wopl/wopl_file.h
- test/CMakeLists.txt
- test/bankmap/CMakeLists.txt
- test/bankmap/bank_map.cpp
- test/common/catch.hpp
- test/common/catch_main.cpp
- utils/midiplay/adlmidiplay.cpp
Rebased on `WIP-banks` branch which adds c++98. The important commit to look at is https://github.com/Wohlstand/libADLMIDI/pull/89/commits/90d76408d83e07e43dbea404ddbb94c0f6305b24.
This adds `adlinsdata2` which is a structure having operator data inside, instead of the numeric references `adlno1` `adlno2`. This can be the new instrument structure to keep them stored in one piece.
Internally, I edit libADLMIDI to use this structure.
But I do not edit `genadldata` and allow it to convert to the same structure as before, because it is more compact in memory. I keep both structures available. There exists a constructor to convert `adlinsdata` to `adlinsdata2`.
There is one impact on implementing libADLMIDI : wherever the `adlno`s are compared for equality, I am now instead comparing the …
> Unified structure for instruments and meta-instruments

- src/adlmidi_bankmap.h
- src/adlmidi_bankmap.tcc
- src/adlmidi_ptr.hpp
C++98 bank map implemented using custom shared pointers.
The shared pointer receives a deleter argument, which is to define in order to invoke `delete[]` on the pointer which is wrapped.
Also changed the more minor things here and there.
> c++98 support for bank map

- src/adlmidi_private.cpp
#92 
I would like to have a discussion on computation of 4op channel count.
It's a code I don't like, for the hazardous way to statically fix the channel count, and also I find it to be nonsensical in several ways.
I know that this thing was Joel's code originally.
1. The dynamic banks counts the blank instruments, which makes total count erroneous for the final estimation. It's a thing I have attempted to fix.
2. There is a modulo 128 applied to the total I find no explanation for, and which I would think is better to remove.
3. I understand the computation of `NumFourOps` like this:
- If there's no 4-ops => 0
- The 4-ops use more than 7/8 of the bank => 6
- The 4-ops use less than 1/8 of the bank => **0** (**can't have any 4-ops in this case??????**)
- Otherwise if it's single chip 1, …
> attempt to rework 4op count computation

- src/adlmidi_bankmap.h
- src/adlmidi_load.cpp
- src/adlmidi_midiplay.cpp
- src/adlmidi_opl3.cpp
- src/adlmidi_private.cpp
- src/adlmidi_private.hpp
This is the storage of structure `adlinsdata2` inside the dynamic map.
Now, all bank storage used by the MIDI player happens is made to happen inside this map.
For embedded banks, when `setEmbeddedBank` is called, it will copy the internal bank into entry 0:0 of the map.
The bank identifier is the 16bit integer PMMMMMMM 0LLLLLLL. (Percussive, MSB, LSB)
A bit operation identifies the bank as melodic or percussion. It's the bit value `OPL3::PercussionTag`.
When the MIDI player won't find a bank, il will fall back to 0:0.
I find it not bad as it is now, but I think later I'll be interested to keep a counter of the number of actual (non-blank) instruments contained in the banks slots.
> bank storage inside dynamic map

- include/adlmidi.h
- src/adldata.hh
- src/adlmidi.cpp
- src/adlmidi_bankmap.h
- src/adlmidi_bankmap.tcc
- src/adlmidi_load.cpp
- src/adlmidi_private.hpp
#59 
This is a simple API for external access of dynamic banks.
Most operations are here, except some I will be interested to add in a moment:
- creating a bank with possibility to reuse a blank bank slot of there exists one. (to add as `ADL_BankAccessFlags`) [1]
- getting the number of banks. I don't have a lot of use for this, and this would enter in naming confusion with the unfortunately existing `adl_getBanksCount`.
To accelerate [1], I wish to keep a counter of used instruments in dynamic banks.
It would be initialized when a bank is loaded either from embedded or WOPL file source, and successively incremented or decremented by following calls of `adl_setInstrument`.
> dynamic instrument API

- CMakeLists.txt
- src/chips/nuked_opl3.cpp
- src/chips/nuked_opl3.h
- src/chips/nuked_opl3_v174.cpp
- src/chips/nuked_opl3_v174.h
Add a HQ resampling option to be used with Nuked OPL.
This will allow to hear a comparison for high sample rates, to compare with original linear interpolation.
Performance-wise, the overhead of resampling is a 48-tap FIR on each channel.
There is a description of the resampling process: http://kokkinizita.linuxaudio.org/linuxaudio/zita-resampler/resampler.html
> optional high-quality resampling

- src/chips/nuked_opl3.cpp
- src/chips/nuked_opl3_v174.cpp
Saturate the additions in the case of HQ resampler
> clamp the outputs of 16bit adding generators

- src/adlmidi_midiplay.cpp
- src/adlmidi_private.hpp
Proposing alternative to the pitchbend fix I'm in disagreement with.
Instead of updating pitch when bend sensitivity events are coming, I do this:
Do NOT premultiply pitchbend with bendsense when the pitchbend event arrives.
Conserve the midi value stored, and wait in order to do this multiplication late, at the time of note-on.
What do you think?
~~Still, I'm not convinced if resetting bend on `resetAllControllers` is a proper thing to do.~~
EDIT it's the good thing to reset pitch bend on this event
> new pitchbend strategy

- src/adlmidi.cpp
- utils/midiplay/adlmidiplay.cpp
The same modification of the version string as in OPNMIDI.
On a side note: I observe now `genadldata` has a failing link step in the HQ build. Undefined references to zita library symbols.
> library version string for HQ variant

- src/adlmidi_midiplay.cpp
- src/adlmidi_private.hpp
Handle resets and master volume.
Master volume handles MSB only for 7bit resolution. It was for a quick solution because it makes formulas simpler to adapt.
> Split midi sequencer and sysex 2

- src/adlmidi_midiplay.cpp
Doing the iteration on channels the same as other code does, because the MIDI channels seem not fixed at 16.
> glide: handle for all the midi channels

- src/adlmidi_midiplay.cpp
This puts a color ID which identifies the MIDI channel in low 4 bits of the channel description.
This extends API to allow implementing a colored output.
(adljack currently has a monochrome output of channels)
Upper bits are reserved for keeping more infos as necessary. (key release was discussed before)
> color attribute for channel descriptor

- include/adlmidi.h
- src/adlmidi.cpp
- src/midi_sequencer.hpp
- src/midi_sequencer_impl.hpp
- utils/midiplay/adlmidiplay.cpp
#30 
This adds an API to set tracks as On/Off/Solo.
One can play solo tracks in `midiplay` with option `--solo N`.
Example of System shock XMI playback
`./build/adlmidiplay genmidi/thm7.xmi --solo 4`
To discuss is the case of SMF, where formats have track 0 as a special track for Meta-events.
Solo mode on another track will make track 0 disabled, and may produce undesired effect.
> Track options

- src/midi_sequencer.hpp
- src/midi_sequencer_impl.hpp
Special case for SMF where timing events of track 0 must be always used.
This keeps `smfFormat` as sequencer variable.
Outside of SMF format: it will be 2 for multi-track XMI, otherwise it will be taken as 0
If invalid value in SMF it has fallback as 1. (which I think to be the most compatible)
I will do the special case in format 0 as well as format 1, to protect of non-standard smf which will lie about their format.
> SMF track 0 on solo/off mode

- src/cvt_xmi2mid.hpp
This modifies the XMI converter of Wildmidi to handle RBRN blocks.
These metadata allow a control change event to jump to one of these numbered blocks (0-127).
It contains a byte offset which points to the start of an event from a EVNT block.
I'm parsing these blocks, and search in their offsets as I go through events.
If it's found, I insert SMF meta events of type 0x6 marker with a recognizable name.
I made it the text ":XBRN:XX" where XX is a hexadecimal branch ID.
Documentation was confusing about endianness used throughout the file format but I found LE to be the one working.
> xmi: convert the RBRN block as MIDI marker

- include/adlmidi.h
- src/adlmidi.cpp
- src/midi_sequencer.hpp
- src/midi_sequencer_impl.hpp
#30 
Implement AIL callback trigger (`thm0.xmi` first track)
I make this controller event a `ST_SPECIAL` in the sequencer, as done for loop events before, and covered under the XMI file format case. But if prefered, it could be left in controller form.
This is modeled after AIL functions `AIL_install_callback`, `AIL_cancel_callback`, except I implement as one function. There is one callback to handle all the triggers, and the trigger value (CC value) is received by the callback.
> xmi: handle AIL callback trigger

- src/adlmidi_load.cpp
Rewrite the conversion behind `adl_getInstrument` which is incorrect
The operators don't have correct values.
In VST programming, I have found this when the bank management doesn't show the same values as OPL3BankEditor. I did a quick check after the patch and operators seems to match.
(with some exceptions as Level, KSR, but because the bank editor has these values inverted)
> fix the conversion of FMIns->ADLI operators

- src/adldata.hh
- src/adlmidi_cvt.hpp
- src/adlmidi_load.cpp
- src/adlmidi_midiplay.cpp
- src/adlmidi_private.cpp
- test/CMakeLists.txt
- test/conversion/CMakeLists.txt
- test/conversion/conversion.cpp
Following your comment on 4op storage
This allows to keep operators 3-4 in program structures which are 2op.
This also eliminates the logic code which uses adlins comparisons for 2op checking and replaces with usage of flags.
I did a quick test.
> preserve the data of operator 3-4 in internal storage, regardless of being 2op/4op

- src/adlmidi_cvt.hpp
- test/conversion/conversion.cpp
There was a loss in the conflicting merge of the 2 last pulls, as conversions were moved to their own files for purposes of testing.
The midi velocity offset stopped being converted after that. This is the fix, and the matching update of unit test.
Since it's trivial and not much is to say of this fix, I'll merge it.
> add midi_velocity_offset in the conversion, and add unit test

- src/adlmidi.cpp
- src/adlmidi_midiplay.cpp
- src/adlmidi_private.hpp
#139
Attempt to fix an inability to conserve programs on changing chip count and others.
It returns ADLMIDI to an older behavior which my programs have relied on. (except `adl_reset` which remains as is)
It provides seamless transition when the setting of emulator or chip count is changed.
It's easy to observe the problem: pick any version of the VST after the big libADLMIDI update, change chip. The programs get reset.
What I do: replace full reset by basic reset, preceded by `realtime_panic` which stops current notes.
> changing synth setup without the full MIDI reset

- include/adlmidi.h
- src/adlmidi_bankmap.h
- src/adlmidi_private.hpp
- src/chips/dosbox/dbopl.cpp
- src/chips/dosbox/dbopl.h
- src/midi_sequencer.hpp
- utils/adlmidi-2/puzzlegame.cc
Fixed GCC Warnings
- warning: this statement may fall through [-Wimplicit-fallthrough=]
Fixed Clang Warnings:
- warning: adding 'unsigned int' to a string does not append to the string [-Wstring-plus-int]
- warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
- warning: commas at the end of enumerator lists are a C++11 extension [-Wc++11-extensions]
Warnings present still not fixed:
- warning: variadic macros are a C99 feature [-Wvariadic-macros]
- warning: anonymous variadic macros were introduced in C++11 [-Wvariadic-macros]
- warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct adlinsdata2'; use assignment or value-initialization instead [-Wclass-memaccess]
- warning: 'strncpy' output may be truncated copying 32 bytes from …
> fix some warnings

- src/adldata.hh
- src/adlmidi.cpp
- src/adlmidi_midiplay.cpp
- src/adlmidi_opl3.cpp
- src/adlmidi_private.cpp
This allows `adlinsdata2` to be a trivial type.
Fixes:
`warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct adlinsdata2'; use assignment or value-initialization instead [-Wclass-memaccess]`
> fix the gcc warning "class-memaccess"

- src/adlmidi.cpp
- src/adlmidi_midiplay.cpp
- src/adlmidi_opl3.cpp
- src/adlmidi_private.hpp
Verification of presence of an emulator passed to `switchEmulator`.
It's a step to allow for a more robust scanning, but especially when some of the emulators will be disabled.
Usually, libADMIDI would be happy to answer OK for a disabled emulator id and default to the first enabled other in that case.
> add safety check for emulator switching

- src/adlmidi_midiplay.cpp
#154 
I have thought of a simple attempt to fix arpeggio issues. It's not tested. :warning: 
It would force an update of timing just at the end of note-on, and before a second note-on which would arrive without having `TickIterators` happened between.
In such a way, it's become possible that a taken channel can reinitialize its `koff` time before a case of note-on coming right after.
In such a way, it could fix the scoring of a next channel selection, which could happen to reselect the already taken channel if the `koff` time outweighs the 4000 point malus for each arpeggio user already on channel.
Do you think of it as correct reasoning?
> early koff update to prevent a bad reuse of channel

- src/cvt_xmi2mid.hpp
This fixes how Warcraft II's tail events are read by XMI's parser.
As a difference with SMF format, XMI reads its delta by summing the continuation bytes, instead of concatenating the bits. (not a very smart way of proceeding when you think of it)
Problem with WildMidi's parser: it forces to stop at the 4th byte.
In this case, the delta is not allowed to exceed the value 4*127=508.
Which is why if you trace Wc2's XMI parsing, you'll see lots of 508s in a sequence, and of course incorrect event data following.
As a fix, I allow it to accumulate its delta without a bounds for the count of bytes read.
**Note**: this doesn't fix the big delta at end of file, which results in very long playback time.
The sequencer must receive its own workaround for this other problem.
Gotta report this fix …
> XMI: fix the VLQ reading procedure

- src/adlmidi_midiplay.cpp
Important bug fix :warning: 
This solves a problem of execution getting stuck in sound processing.
In following vibrato depth calculation, the value is typed as unsigned, and creates an expression result as a very large integer. This large integer gets into the frequency calculation formula and creates an infinity result. It puts the program in a situation of infinite loop at OPL3::noteOn.
> fix a case of miscalculation and infinite loop

- include/adlmidi.h
- src/adlmidi.cpp
Do you agree with such ability to return 4op count to the calculated value?
From the plugin, I am invoking `adlRefreshNumCards` and it's a big hack, because I don't seem to have another possibility at disposal.
> API to return 4op channels to the original count

- banks.ini
- utils/gen_adldata/scrapped.txt
Found another small error in metadata.
This one, it's just in prefix which I don't know what its usage is. Adldata seems unaffected.
> fix a miswritten name: sneakernets

- src/adlmidi_opl3.cpp
Fixes an uninitialized use which is difficult to track.
With embedded bank disabled, the bank setup never initializes the value at `adl_init`, which depends on values for channels setup as rhythm mode or not, and also modulator scaling to invoke codes which silence all notes.
> provide default initialization for bank setup

- src/chips/dosbox_opl3.cpp
- utils/vlc_codec/libadlmidi.c
Rename DOSBox from a previous naming "DosBox".
It's the preferred way of writing from most of places where seen.
> rename DOSBox using preferred casing

- include/adlmidi.h
- src/adlmidi.cpp
- src/adlmidi_opl3.cpp
- src/adlmidi_private.hpp
Add some functions to be able to track chip's global state which is current: tremolo flags, volume model.
> access into global chip settings

- src/adlmidi.cpp
Removing a redundant null check remaining I have just noticed.
> eliminate a redundant null check

- src/chips/dosbox/dbopl.cpp
- src/chips/dosbox/dbopl.h
#178 
A quick-made modification to DOSBox emulation permitting to cache the table computations which depend on sample rate.
Please check.
> dosbox: add caching of the attack rate computation

- CMakeLists.txt
- Detect the standard installation paths of OS distributions.
A fedora guy has hinted me about needing this to have the libraries in correct places where the distributions intend them to be, especially in some multi-lib layouts.
One can override this by `CMAKE_INSTALL_*DIR`.
- Install a version symlink for the shared library.
This will let a linker use a version tagged library identifier.
> improvement on the installation procedure based on CMake

- utils/midiplay/adlmidiplay.cpp
Add a call `fmod` to fix the minutes. Also remove the `floor` calls redundant because of casts.
MIDI file for test [thrust.mid.gz](https://github.com/Wohlstand/libADLMIDI/files/2568453/thrust.mid.gz)
before `11:673:58,221`
after `11:13:58,221`
> fix minute display on 1+ hour tracks

- src/adlmidi_midiplay.cpp
- src/adlmidi_midiplay.hpp
- src/structures/pl_list.hpp
- src/structures/pl_list.tcc
Here is a work in progress for generic internal data structures.
The `pl_list` is a generic container with STL-like behavior, with particularities.
- the `value_type` is the linked-list cell `pl_cell<T>` (it is not `T`)
- the cell consists of a pair of link pointers and value
- the wrapped value is obtained by `mycell->value`
- the list has a sentinel element to mark the end of list.
1. it's the cell refered by the `end()` iterator
2. it's the only case of cell which does not contain value
3. it can be navigated back from it, meaning you can safely do `operator--` on the end iterator
- the end element has `next` to null, so end of list can be checked on this condition `iterator.is_end()`, it's not needed the inconvenience of comparing to `end()`
- (supports external buffering policy. but …
> Std structures

- src/adlmidi_midiplay.cpp
because `cell->next` is not null in this case, it points at the tail pseudo-cell which enables going back from the end iterator.
> fix `describeChannels` iteration problem on the generic list structure

- src/chips/opal/opal.hpp
This fixes the KSL computation of Opal which is incorrect.
From YMF262 docs: some values are in unnatural order, which make it misleading.
KSL | 0 | 1 | 2 | 3
|---|---|---|---|---|
Attenuation | 0 | 3 dB/oct | 1.5 dB/oct | 6 dB/oct
> opal: fix the computation of KSL

- src/adlmidi_opl3.cpp
Add all emulators to the preprocessor directive that ensures at least one is enabled.
This was broken when I tried to build with only `OPAL` or `JAVA` emulator enabled.
> Update emulators enabled check

- src/chips/dosbox/dbopl.cpp
This should ensure dosbox initialization and usage in sequential manner.
Mutex functions are not called after the first time.
> dosbox: thread-safe global initialization

- utils/gen_adldata/file_formats/load_ail.h
Consider out of bounds range of AIL operators as 0.
Fixes heap-buffer-overflow by 1 element.
> genadldata: fix invalid access in the AIL reader

- CMakeLists.txt
It's a good practice to respect BUILD_SHARED_LIBS setting. 
It will be easier to integrate the library to projects and build systems.
> CMake: respect BUILD_SHARED_LIBS setting

- CMakeLists.txt
- libADLMIDI-config.cmake.in
These changes will make it much easier for external users to integrate the library. Easy as:
```
find_package(libADLMIDI CONFIG REQUIRED)
...
target_link_libraries(main PRIVATE libADLMIDI::ADLMIDI)
```
- Fixed absolute path in includes
- Added static/shared targets export
- Had to increase CMake's min version for aliasing local targets in confg.cmake, there is an ugly workaround if you don't want to do this
> CMake: added package export; fixed includes

- src/chips/nuked/LICENSE
- src/chips/nuked/nukedopl3.c
- src/chips/nuked/nukedopl3.h
I took the latest Nuked OPL 1.8 code from https://github.com/nukeykt/Nuked-OPL3 and applied changes from libADLMIDI.
It's faster than the old Nuked OPL 1.8 code in libADLMIDI.
The 32-bit version (x86) was faster than Nuked OPL 1.7 version in my testing.
The 64-bit version (x64) was slower than Nuked OPL 1.7 version.
> Import latest Nuked OPL 1.8 code
