Wohlstand/libADLMIDI

src/adlmidi.cpp

As discussed in [OPNMIDI merge request](https://github.com/Wohlstand/libOPNMIDI/pull/10).
Please check if it works.

apply a correct buffer offset to channels

---

src/chips/opl_chip_base.cpp
src/chips/opl_chip_base.h

Just to keep ADLMIDI on the same page.

general 32bit generator methods, like OPNMIDI

---

src/adlmidi_midiplay.cpp
src/adlmidi_private.hpp

This is the code discussed in #65 made into a PR.
It is step 1 into making ADLMIDI hard-RT compliant.
As far as I can tell this code plays back without issues.
Second, I need to think how to handle the Phys map which is present in every NoteInfo.

transform the note map into a fixed array

---

src/adlmidi_midiplay.cpp
src/adlmidi_private.hpp

Prefer this PR to #69 
It's the same content but rolled in a single commit instead of series of bug fixes..

hard-RT: elimination of the user map

---

src/adlmidi_private.hpp

The same null pointer fix as OPNMIDI

fix a null problem when allocating the last user cell

---

src/adlmidi_midiplay.cpp
src/adlmidi_private.hpp

Same as in libOPNMIDI, including fixes added later

implement copy for OplChannel, and move implementations in .cpp

---

src/chips/dosbox/dbopl.cpp
src/chips/dosbox/dbopl.h
src/chips/dosbox_opl3.cpp

#97 
Update Dosbox to SVN trunk
I change all things necessary to make it build and include the modifications from Joel.
- decouple from Dosbox core
- include in it the needed routines of ChipBase, and the ability to generate adding

update Dosbox OPL

---

src/chips/opl_chip_base.tcc

don't forget to increment sample pointer in generate16

---

src/adlmidi_midiplay.cpp
src/adlmidi_private.cpp
src/adlmidi_private.hpp

Allow portamento to be updated by MIDI::Tick.
Disables audio tick handler.

Poly portamento2

---

include/adlmidi.h
src/adlmidi.cpp
src/adlmidi_midiplay.cpp
src/adlmidi_private.hpp

An implementation of sysex with API which was integrated in the sequencer, and tested on real MIDI files.
It's only the framework, no implementation of message themselves, athough it has recognition for few basic ones.

basic framework of sysex handling and sequencer support

---

include/adlmidi.h
src/adlmidi.cpp

Proposal to implement like suggested in #125. Not tried

embedded bank loading API into multi-bank

---

CMakeLists.txt
utils/xmi2mid/xmi2mid.cpp

As debugging help for inspecting XMI files

provide XMI to MID conversion as tool

---

utils/midiplay/adlmidiplay.cpp

Add a command line argument to play back just a subset of the tracks.
Also add descriptions of new flags added.
Usage is `--only 0,1,2,3`.
for testing convenience related to issue #134

midiplay: add argument --only

---

src/adlmidi_midiplay.cpp

#136 
proposal to implement the GS bank change as is described.
Is there any test case of this?

bank fallback for GS mode

---

src/adlmidi_opl3.cpp

This reassigns all the channel categories after a change of four-op count.
It fixes the four-ops categories which stay assigned after increasing the count and then decreasing.

reassign the channel categories after num4ops was decreased

---

banks.ini
src/adldata.cpp
utils/gen_adldata/scrapped.txt

Just fixing a few typos. Jamie O'Connell/Apogee

Fixing some miswritten names in the metadata

---

src/wopl/wopl_file.c
test/CMakeLists.txt
test/wopl-file/CMakeLists.txt
test/wopl-file/wopl_file.cpp

fixes #168 
fixes #169 
adds unit test, same as libOPNMIDI

wopl: bug fix and test

---

src/adlmidi.cpp
src/adlmidi_private.hpp

#172 
Harmonize the way how are performed the null checks in the public functions, and some other things.

have consistent null checks and returns

---

src/chips/dosbox/dbopl.cpp

For some reason I rethought of last Dosbox changes, and came the "damn" moment about a mistake made.
As the cache entry is referred inside its vector container and the lock is released, it could be that another pushes to the vector near the same moment, invalidating the item's reference. It can do an invalid access after the line 1461.
Not a likely problem for sure, here is the fix.

dosbox: fix a potential cache access problem

---

CMakeLists.txt
libADLMIDI.pc.in

Implements the pkg-config feature #186

Provide pkg-config support

---

src/wopl/wopl_file.c
src/wopl/wopl_file.h

Implement into libADLMIDI the changes made in wopl_file.
libADLMIDI's has also a fix which isn't copied on OPL3BE side, so it will need another syncing.

update the WOPL library with fixes

---

src/adlmidi_midiplay.cpp
src/adlmidi_midiplay.hpp
src/adlmidi_sequencer.cpp
src/midi_sequencer_impl.hpp

Same work as Wohlstand/libOPNMIDI@ 71d0efe

drum note length extension

---

src/adlmidi_midiplay.cpp

prevent duplicate locations in users sets

---

CMakeLists.txt
include/adlmidi.h
src/adlmidi_opl3.cpp
src/chips/opal/README
src/chips/opal_opl3.cpp
src/chips/opal_opl3.h
utils/midiplay/adlmidiplay.cpp

opal.cpp not included in sources, add manually

support the Opal emulator

---

src/chips/opal/README
src/chips/opal/opal-pan.diff
src/chips/opal_opl3.cpp

+patch Opal emulator found here
https://gist.github.com/jpcima/d4f6b99c31f3cd772a373887f2d3f318

opal: enable use of soft panning

---

src/chips/opal/opal.hpp

opal: fix envelope delay between stage transitions

---

utils/adlmidi-2/CMakeLists.txt
utils/adlmidi-2/midiplay.cc

Fix issue Wohlstand/libADLMIDI#239 by using _popen() plus a couple of other minor tweaks

Fix issue Wohlstand/libADLMIDI#239

---

src/chips/esfmu/esfm.c
src/chips/esfmu/esfm.h
src/chips/esfmu/esfm_registers.c
src/chips/esfmu_opl3.cpp

This was simple enough to implement.

Added full panning support for ESFMu
